# Generated by Django 5.1.6 on 2025-03-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promova_app', '0002_alter_users_is_active_alter_users_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
    ]
